version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    ECR_REPOSITORY: "jacobwaltersmovies"
    ECS_CLUSTER: "devcluster2"
    ECS_SERVICE: "jacobwaltersmovies3"
    TASK_DEFINITION: "jacobwaltersmovies"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 533267094010.dkr.ecr.$AWS_REGION.amazonaws.com


  build:
    commands:
      - echo Building the Docker image...
      - docker build -t cdk-hnb659fds-container-assets-533267094010-us-east-1 .
  post_build:
    commands:
      - echo "calculating hash with command IMAGE_HASH=$(sudo docker save cdk-hnb659fds-container-assets-533267094010-us-east-1 | md5sum | awk '{ print $1 }')"
      - IMAGE_HASH=$(sudo docker save cdk-hnb659fds-container-assets-533267094010-us-east-1 | md5sum | awk '{ print $1 }')
      - echo IMAGE_HASH:$IMAGE_HASH
      - echo Pushing the Docker images...
      - docker tag cdk-hnb659fds-container-assets-533267094010-us-east-1:latest  533267094010.dkr.ecr.us-east-1.amazonaws.com/cdk-hnb659fds-container-assets-533267094010-us-east-1:$IMAGE_HASH
      - docker push 533267094010.dkr.ecr.us-east-1.amazonaws.com/cdk-hnb659fds-container-assets-533267094010-us-east-1:$IMAGE_HASH
      