version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    ECR_REPOSITORY: "jacobwaltersmovies"
    ECS_CLUSTER: "devcluster2"
    ECS_SERVICE: "jacobwaltersmovies3"
    TASK_DEFINITION: "jacobwaltersmovies"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.$AWS_REGION.amazonaws.com
      
      - export IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - export REPOSITORY_URI=$(aws ecr describe-repositories --repository-names $ECR_REPOSITORY --query 'repositories[0].repositoryUri' --output text)
      
      - echo "Using image tag: $IMAGE_TAG"
      - echo "Repository URI: $REPOSITORY_URI"

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG ./next
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest

      - echo Updating ECS task definition...
      - aws ecs describe-task-definition --task-definition $TASK_DEFINITION --query taskDefinition > task-definition.json

      # Modify the task definition with the new image
      - jq --arg IMAGE "$REPOSITORY_URI:$IMAGE_TAG" '.containerDefinitions[0].image = $IMAGE' task-definition.json > new-task-def.json
      - aws ecs register-task-definition --cli-input-json file://new-task-def.json

      # Get the new task definition revision
      - export NEW_REVISION=$(aws ecs describe-task-definition --task-definition $TASK_DEFINITION --query "taskDefinition.revision" --output text)

      - echo Deploying updated task to ECS...
      - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --task-definition $TASK_DEFINITION:$NEW_REVISION --force-new-deployment
